name: Publish Github Package
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@relucent-software'
      - run: npm ci
      - run: npx lerna bootstrap
      - run: npx lerna run lint
      - run: npx lerna run build -- --env production
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: packages/logos/dist/*
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: npx lerna publish from-git --no-private --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}